apiVersion: apps/v1
kind: Deployment
metadata:
  name: drama
  namespace: outerpark
  labels:
    app: drama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drama
  template:
    metadata:
      labels:
        app: drama
    spec:
      containers:
        - name: drama
          image: user01skccacr.azureacr.io/drama:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
